openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    Contact book
tags:
  - name: Contacts
    description: operations about contacts
servers:
  - url: https://nodejs-hw-4szr.onrender.com
paths:
  /contacts:
    get:
      $ref: ../src/swagger/path/contacts/get.yaml
    post:
      $ref: ../src/swagger/path/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../src/swagger/path/contacts/{id}/get.yaml
    patch:
      $ref: ../src/swagger/path/contacts/{id}/patch.yaml 
    delete:
      $ref: ../src/swagger/path/contacts/{id}/delete.yaml
  
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
